DROP TABLE IF EXISTS prices;
CREATE TABLE prices (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id        BIGINT         NOT NULL,
    start_date      TIMESTAMP      NOT NULL,
    end_date        TIMESTAMP      NOT NULL,
    price_list      INT            NOT NULL,
    product_id      BIGINT         NOT NULL,
    priority        INT            NOT NULL,
    price           DECIMAL(10, 2) NOT NULL,
    curr            CHAR(3)        NOT NULL,
    last_update     TIMESTAMP,
    last_update_by  VARCHAR(50)
);